## Apply Machine Learning with some preprocessing and scikit-learn
Datasets used :
1. Real Estate Price Prediction: https://raw.githubusercontent.com/shivshaktisahoo/test/main/Real%20estate.csv
2. Medical Cost Personal Datasets: https://raw.githubusercontent.com/shivshaktisahoo/test/main/insurance.csv


In [ ]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (15,5)
import sklearn
from sklearn.linear_model import LinearRegression

### 1. Real Estate Price Prediction

In [ ]:
dataset1 = pd.read_csv("https://raw.githubusercontent.com/shivshaktisahoo/test/main/Real%20estate.csv")
dataset1.head()

No  X1 transaction date  ...  X6 longitude  Y house price of unit area
0   1             2012.917  ...     121.54024                        37.9
1   2             2012.917  ...     121.53951                        42.2
2   3             2013.583  ...     121.54391                        47.3
3   4             2013.500  ...     121.54391                        54.8
4   5             2012.833  ...     121.54245                        43.1

[5 rows x 8 columns]

In [ ]:
# dataset1.pop("No") # Removed Unnecessary Column
# dataset1.head()
# list1 = list(dataset1['X1 transaction date'])
# list1
# list2 = [int(list1[i]) for i in range(len(list1))]
# list2
# dataset1['X1 transaction date']=list2
# dataset1 = dataset1.drop(['No','X1 transaction date'], axis=1)
# dataset1.head()

In [ ]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   No                                      414 non-null    int64  
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64  
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [ ]:
reg1 = LinearRegression()
x = dataset1.drop(['No','X1 transaction date','Y house price of unit area'], axis=1)
y = dataset1['Y house price of unit area']
x_train, x_test, y_train, y_test =  sklearn.model_selection.train_test_split(x,y,test_size=0.1)

In [ ]:
reg1.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg1.coef_, reg1.intercept_

(array([-3.10983523e-01, -4.28788116e-03,  1.06769752e+00,  2.64884979e+02,
        -1.95993833e+01]), -4188.188682488224)

In [ ]:
reg1.score(x_train,y_train)

0.5961942412944226

In [ ]:
print(f"Training result is {reg1.score(x_train,y_train)*100:.3f}%")

Training result is 59.619%


In [ ]:
reg1.score(x_test,y_test)

0.32365338428223084

In [ ]:
print(f"Testing result is {reg1.score(x_test,y_test)*100:.3f}%")

Testing result is 32.365%


In [ ]:
reg1.predict(x_test)

array([44.252987  , 32.48312465, 39.2369192 , 32.31245254, 46.4327231 ,
       45.40475433, 38.48648762, 27.66892788, 13.90296551, 43.82195225,
       41.83213149, 33.95377089, 41.35978449, 42.06635164, 37.58460221,
       53.30590726, 41.96098185, 41.28939513, 23.63178665, 44.5835743 ,
       40.4509032 , 39.08106835, 54.32575129, 45.04147363, 45.37365597,
       30.61711637, 38.49503763, 41.96820599, 15.28985933, 29.37138178,
       53.36810396, 40.14132445, 50.16342017, 44.83703301, 45.99633269,
       23.71599863, 36.03565419, 31.15059826, 46.71159479, 42.28406699,
       42.90706486, 41.42198119])

how to plot multidimensional axis, as
x and y are not in same size

In [ ]:
x_train

X2 house age  ...  X6 longitude
160           3.5  ...     121.53756
147           3.2  ...     121.54494
344          34.6  ...     121.51550
149          34.9  ...     121.54245
249          18.0  ...     121.47516
..            ...  ...           ...
129          38.5  ...     121.54162
140          16.2  ...     121.54348
183          17.0  ...     121.50381
24           39.6  ...     121.53885
219          29.3  ...     121.53655

[372 rows x 5 columns]

### 2. Medical Cost Personal Datasets

In [ ]:
dataset2 = pd.read_csv("https://raw.githubusercontent.com/shivshaktisahoo/test/main/insurance.csv")
dataset2

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
dataset2.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
x1 = dataset2.drop(['charges'], axis=1)
y1 = dataset2['charges'] 

In [ ]:
x1 = pd.get_dummies(x1)
x1

age     bmi  ...  region_southeast  region_southwest
0      19  27.900  ...                 0                 1
1      18  33.770  ...                 1                 0
2      28  33.000  ...                 1                 0
3      33  22.705  ...                 0                 0
4      32  28.880  ...                 0                 0
...   ...     ...  ...               ...               ...
1333   50  30.970  ...                 0                 0
1334   18  31.920  ...                 0                 0
1335   18  36.850  ...                 1                 0
1336   21  25.800  ...                 0                 1
1337   61  29.070  ...                 0                 0

[1338 rows x 11 columns]

In [ ]:
reg2 = LinearRegression()
x_train2, x_test2, y_train2, y_test2 =  sklearn.model_selection.train_test_split(x1,y1,test_size=0.1)

In [ ]:
reg2.fit(x_train2, y_train2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg2.coef_, reg2.intercept_

(array([   254.49412297,    321.57639286,    475.91553129,    139.21094913,
          -139.21094913, -11999.65790901,  11999.65790901,    556.45436521,
            27.74217843,   -392.1780824 ,   -192.01846123]), 58.92441144961413)

In [ ]:
reg2.score(x_train2,y_train2)
print(f"Training result is {reg2.score(x_train2,y_train2)*100:.3f}%")


Training result is 74.919%


In [ ]:
reg2.score(x_test2,y_test2)
print(f"Testing result is {reg2.score(x_test2,y_test2)*100:.3f}%")

Testing result is 76.154%


In [ ]:
reg2.predict(x_test2)

array([ 5936.27504847, 35465.29002194, 14784.71575457, 11100.06719161,
       32486.94284825, 27288.39789137,  6634.02027325,  8720.49800528,
       33340.22825367,   301.9004518 , 32015.07020927, 29387.02077669,
       30026.90815749, 36340.57411509, 10388.36821561, 14906.91478386,
       12550.09612513,  8456.91633077, 11412.66968393,  -577.81966011,
        7565.60426674,  5518.60409352,  5624.34664051,  -648.61610754,
        6618.15405417,  4070.92642033,  7154.1508401 , 11280.11302612,
        9819.92519754, 28774.34320143, 27606.38715906, 29711.51450879,
       30195.47125018,  2211.71213598, 13956.07927255,  4129.72486523,
       12654.27403706,  6240.48476598,  2619.21660969,  1318.56598241,
       15164.30177999, 16871.66974107,  5144.27880096, 15149.59005403,
       27239.90491428,  2714.60152815,  8426.7915145 , 31095.32478019,
        9382.54525359,  1458.58739559,  3668.05838402,  7976.78686833,
       11045.48814117,  1449.91064418,  6837.24938185,  1244.73909433,
      